export const CategoryFilters = [
  { name: "Education 🎓", value: "education" },
  { name: "Yeeeah, science! 🔬", value: "science" },
  { name: "Art 🎭", value: "art" },
  { name: "Sport ⚽", value: "sport" },
  { name: "Technology 💻", value: "technology" },
  { name: "Music 🎵", value: "music" },
  { name: "Travel ✈️", value: "travel" },
  { name: "Food 🍔", value: "food" },
  { name: "Health 🏥", value: "health" },
  { name: "Fashion 👗", value: "fashion" },
  { name: "History 📜", value: "history" },
  { name: "Science Fiction 🚀", value: "scienceFiction" },
  { name: "Business 💼", value: "business" },
  { name: "Nature 🌿", value: "nature" },
  { name: "Gaming 🎮", value: "gaming" },
  { name: "Movies 🎬", value: "movies" },
  { name: "Photography 📷", value: "photography" },
  { name: "Pets 🐾", value: "pets" },
  { name: "Self-Improvement 🌟", value: "selfImprovement" },
];
